packages:
  - libs/*
  - svcs/*
  - apps/*
  - tools/*
onlyBuiltDependencies:
  - esbuild
catalog:
  '@hono/node-server': '^1.19.6'
  '@types/node': '^24.10.1'
  'commander': '^14.0.2'
  'hono': '^4.10.6'
  'prettier-plugin-tailwindcss': '^0.7.1'
  'prettier': '^3.6.2'
  'solid-js': '^1.9.10'
  'tsx': '^4.20.6'
  'typescript': '^5.9.3'
  'vite-plugin-solid': '^2.11.10'
  'vite': '^7.2.4'
  'vitest': '^4.0.13'
