packages:
  - libs/*
  - svcs/*
  - apps/*
  - tools/*
onlyBuiltDependencies:
  - esbuild
catalog:
  "@hono/node-server": "^1.8.0"
  "@types/node": "^20.11.0"
  "commander": "^12.0.0"
  "hono": "^4.0.0"
  "prettier-plugin-tailwindcss": "^0.7.1"
  "prettier": "^3.6.2"
  "solid-js": "^1.8.0"
  "tsx": "^4.19.0"
  "typescript": "^5.7.0"
  "vite-plugin-solid": "^2.8.0"
  "vite": "^5.0.0"